version: 2.1
orbs:
  codecov: codecov/codecov@1.0.5
aliases:
  - &restore-cache
    keys:
      - v2-dependencies-{{ .Branch }}-{{ checksum "yarn.lock" }}
      # Fallback in case checksum fails
      - v2-dependencies-{{ .Branch }}-

  - &save-cache
    paths:
      - node_modules
      - website/node_modules
    key: v2-dependencies-{{ .Branch }}-{{ checksum "yarn.lock" }}

  - &install yarn --no-progress --frozen-lockfile

jobs:
  build:
    working_directory: ~/flyback
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore_cache: *restore-cache
      - run: yarn --no-progress --frozen-lockfile
      - save_cache: *save-cache
      - run: yarn build 

  test-node-10:
    working_directory: ~/flyback
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore_cache: *restore-cache
      - run: *install
      - save_cache: *save-cache
      - run:
          command: yarn test

  test-node-11:
    working_directory: ~/flyback
    docker:
      - image: circleci/node:11
    steps:
      - checkout
      - restore_cache: *restore-cache
      - run: *install
      - save_cache: *save-cache
      - run:
          command: yarn test

# Workflows enables us to run multiple jobs in parallel
workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - test-node-8
      - test-node-10
      - test-node-11 # current
